export const validEnv = {
  APP_PORT: "3000",
  DATABASE_PATH: ":memory:",
  GROOM_NAME: "Budi Setiawan",
  GROOM_SHORT_NAME: "Budi",
  GROOM_INSTAGRAM_HANDLE: "@budi",
  GROOM_INSTAGRAM_URL: "https://instagram.com/budi",
  BRIDE_NAME: "Widia Hasmiati",
  BRIDE_SHORT_NAME: "Widia",
  BRIDE_INSTAGRAM_HANDLE: "@widia",
  BRIDE_INSTAGRAM_URL: "https://instagram.com/widia",
  COUNTDOWN_TARGET: "2026-12-31T09:00:00+07:00",
  AKAD_DATE: "2026-12-31",
  AKAD_TIME: "09:00 WIB",
  AKAD_VENUE: "Masjid",
  AKAD_ADDRESS: "Jalan Akad",
  AKAD_MAP_URL: "https://maps.google.com/akad",
  RECEPTION_DATE: "2027-01-01",
  RECEPTION_TIME: "11:00 WIB",
  RECEPTION_VENUE: "Gedung",
  RECEPTION_ADDRESS: "Jalan Resepsi",
  RECEPTION_MAP_URL: "https://maps.google.com/resepsi",
  BANK_1_NAME: "BCA",
  BANK_1_ACCOUNT_NUMBER: "123456",
  BANK_1_ACCOUNT_HOLDER: "Budi",
  BANK_2_NAME: "BRI",
  BANK_2_ACCOUNT_NUMBER: "654321",
  BANK_2_ACCOUNT_HOLDER: "Widia"
};
